const initialTransactions = [
  {
    id: "TXN-1001",
    customer: { name: "Aditya Sharma", email: "aditya.sharma@example.com", tier: "Gold" },
    amount: 7999,
    paymentMethod: "Card",
    failureReason: "bank_declined",
    retryCount: 1,
    customerSuccessRate: 0.92,
    previousSuccessfulPayments: 14,
    transactionAge: 1.2,
    timestamp: new Date(Date.now() - 1.2 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1002",
    customer: { name: "Priya Patel", email: "priya.p@example.com", tier: "Silver" },
    amount: 2499,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 0,
    customerSuccessRate: 0.88,
    previousSuccessfulPayments: 8,
    transactionAge: 0.5,
    timestamp: new Date(Date.now() - 0.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1003",
    customer: { name: "Rahul Verma", email: "rahul.v@example.com", tier: "Platinum" },
    amount: 14999,
    paymentMethod: "Net Banking",
    failureReason: "network_error",
    retryCount: 0,
    customerSuccessRate: 0.95,
    previousSuccessfulPayments: 22,
    transactionAge: 0.2,
    timestamp: new Date(Date.now() - 0.2 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1004",
    customer: { name: "Sneha Reddy", email: "sneha.r@example.com", tier: "Bronze" },
    amount: 4999,
    paymentMethod: "Card",
    failureReason: "expired_card",
    retryCount: 2,
    customerSuccessRate: 0.40,
    previousSuccessfulPayments: 2,
    transactionAge: 14.5,
    timestamp: new Date(Date.now() - 14.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1005",
    customer: { name: "Vikram Malhotra", email: "vikram.m@example.com", tier: "Gold" },
    amount: 12500,
    paymentMethod: "UPI",
    failureReason: "insufficient_funds",
    retryCount: 1,
    customerSuccessRate: 0.75,
    previousSuccessfulPayments: 9,
    transactionAge: 3.8,
    timestamp: new Date(Date.now() - 3.8 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1006",
    customer: { name: "Ananya Deshmukh", email: "ananya.d@example.com", tier: "Silver" },
    amount: 899,
    paymentMethod: "UPI",
    failureReason: "authentication_failure",
    retryCount: 0,
    customerSuccessRate: 0.65,
    previousSuccessfulPayments: 4,
    transactionAge: 2.1,
    timestamp: new Date(Date.now() - 2.1 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1007",
    customer: { name: "Rohan Gupta", email: "rohan.g@example.com", tier: "Gold" },
    amount: 18999,
    paymentMethod: "Card",
    failureReason: "bank_declined",
    retryCount: 0,
    customerSuccessRate: 0.94,
    previousSuccessfulPayments: 18,
    transactionAge: 0.8,
    timestamp: new Date(Date.now() - 0.8 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1008",
    customer: { name: "Kavya Nair", email: "kavya.n@example.com", tier: "Bronze" },
    amount: 3200,
    paymentMethod: "Wallet",
    failureReason: "insufficient_funds",
    retryCount: 3,
    customerSuccessRate: 0.35,
    previousSuccessfulPayments: 1,
    transactionAge: 28.0,
    timestamp: new Date(Date.now() - 28.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1009",
    customer: { name: "Arjun Mehta", email: "arjun.m@example.com", tier: "Platinum" },
    amount: 25000,
    paymentMethod: "Net Banking",
    failureReason: "network_error",
    retryCount: 1,
    customerSuccessRate: 0.98,
    previousSuccessfulPayments: 31,
    transactionAge: 1.0,
    timestamp: new Date(Date.now() - 1.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1010",
    customer: { name: "Meera Joshi", email: "meera.j@example.com", tier: "Silver" },
    amount: 1599,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 0,
    customerSuccessRate: 0.82,
    previousSuccessfulPayments: 6,
    transactionAge: 4.5,
    timestamp: new Date(Date.now() - 4.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1011",
    customer: { name: "Karan Singh", email: "karan.s@example.com", tier: "Bronze" },
    amount: 6499,
    paymentMethod: "Card",
    failureReason: "authentication_failure",
    retryCount: 1,
    customerSuccessRate: 0.50,
    previousSuccessfulPayments: 3,
    transactionAge: 6.2,
    timestamp: new Date(Date.now() - 6.2 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1012",
    customer: { name: "Divya Agarwal", email: "divya.a@example.com", tier: "Gold" },
    amount: 9999,
    paymentMethod: "Card",
    failureReason: "expired_card",
    retryCount: 0,
    customerSuccessRate: 0.91,
    previousSuccessfulPayments: 15,
    transactionAge: 8.4,
    timestamp: new Date(Date.now() - 8.4 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1013",
    customer: { name: "Siddharth Rao", email: "siddharth.r@example.com", tier: "Silver" },
    amount: 3499,
    paymentMethod: "UPI",
    failureReason: "bank_declined",
    retryCount: 2,
    customerSuccessRate: 0.60,
    previousSuccessfulPayments: 5,
    transactionAge: 12.0,
    timestamp: new Date(Date.now() - 12.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1014",
    customer: { name: "Neha Saxena", email: "neha.s@example.com", tier: "Platinum" },
    amount: 31500,
    paymentMethod: "Net Banking",
    failureReason: "bank_declined",
    retryCount: 0,
    customerSuccessRate: 0.96,
    previousSuccessfulPayments: 27,
    transactionAge: 0.3,
    timestamp: new Date(Date.now() - 0.3 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1015",
    customer: { name: "Manish Kumar", email: "manish.k@example.com", tier: "Bronze" },
    amount: 1200,
    paymentMethod: "Wallet",
    failureReason: "network_error",
    retryCount: 0,
    customerSuccessRate: 0.70,
    previousSuccessfulPayments: 7,
    transactionAge: 2.5,
    timestamp: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1016",
    customer: { name: "Ishita Roy", email: "ishita.r@example.com", tier: "Gold" },
    amount: 8499,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 1,
    customerSuccessRate: 0.89,
    previousSuccessfulPayments: 11,
    transactionAge: 1.8,
    timestamp: new Date(Date.now() - 1.8 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1017",
    customer: { name: "Gaurav Bhatt", email: "gaurav.b@example.com", tier: "Silver" },
    amount: 5500,
    paymentMethod: "Card",
    failureReason: "insufficient_funds",
    retryCount: 0,
    customerSuccessRate: 0.62,
    previousSuccessfulPayments: 4,
    transactionAge: 5.1,
    timestamp: new Date(Date.now() - 5.1 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1018",
    customer: { name: "Pooja Banerjee", email: "pooja.b@example.com", tier: "Gold" },
    amount: 11200,
    paymentMethod: "Card",
    failureReason: "expired_card",
    retryCount: 1,
    customerSuccessRate: 0.87,
    previousSuccessfulPayments: 13,
    transactionAge: 18.2,
    timestamp: new Date(Date.now() - 18.2 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1019",
    customer: { name: "Amitav Das", email: "amitav.d@example.com", tier: "Bronze" },
    amount: 750,
    paymentMethod: "UPI",
    failureReason: "authentication_failure",
    retryCount: 3,
    customerSuccessRate: 0.30,
    previousSuccessfulPayments: 1,
    transactionAge: 32.0,
    timestamp: new Date(Date.now() - 32.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1020",
    customer: { name: "Ruchi Pandey", email: "ruchi.p@example.com", tier: "Platinum" },
    amount: 42000,
    paymentMethod: "Net Banking",
    failureReason: "network_error",
    retryCount: 0,
    customerSuccessRate: 0.97,
    previousSuccessfulPayments: 38,
    transactionAge: 0.1,
    timestamp: new Date(Date.now() - 0.1 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1021",
    customer: { name: "Tarun Kapoor", email: "tarun.k@example.com", tier: "Silver" },
    amount: 3999,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 0,
    customerSuccessRate: 0.84,
    previousSuccessfulPayments: 9,
    transactionAge: 0.9,
    timestamp: new Date(Date.now() - 0.9 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1022",
    customer: { name: "Simran Kaur", email: "simran.k@example.com", tier: "Gold" },
    amount: 6800,
    paymentMethod: "Card",
    failureReason: "bank_declined",
    retryCount: 1,
    customerSuccessRate: 0.90,
    previousSuccessfulPayments: 16,
    transactionAge: 2.7,
    timestamp: new Date(Date.now() - 2.7 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1023",
    customer: { name: "Deepak Mishra", email: "deepak.m@example.com", tier: "Bronze" },
    amount: 1450,
    paymentMethod: "Wallet",
    failureReason: "insufficient_funds",
    retryCount: 1,
    customerSuccessRate: 0.48,
    previousSuccessfulPayments: 2,
    transactionAge: 7.5,
    timestamp: new Date(Date.now() - 7.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1024",
    customer: { name: "Nandini Chawla", email: "nandini.c@example.com", tier: "Gold" },
    amount: 15400,
    paymentMethod: "UPI",
    failureReason: "bank_declined",
    retryCount: 0,
    customerSuccessRate: 0.93,
    previousSuccessfulPayments: 20,
    transactionAge: 1.4,
    timestamp: new Date(Date.now() - 1.4 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1025",
    customer: { name: "Varun Sharma", email: "varun.s@example.com", tier: "Silver" },
    amount: 2999,
    paymentMethod: "Card",
    failureReason: "authentication_failure",
    retryCount: 0,
    customerSuccessRate: 0.78,
    previousSuccessfulPayments: 7,
    transactionAge: 3.1,
    timestamp: new Date(Date.now() - 3.1 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1026",
    customer: { name: "Shweta Kulkarni", email: "shweta.k@example.com", tier: "Platinum" },
    amount: 22000,
    paymentMethod: "Card",
    failureReason: "expired_card",
    retryCount: 0,
    customerSuccessRate: 0.95,
    previousSuccessfulPayments: 29,
    transactionAge: 4.0,
    timestamp: new Date(Date.now() - 4.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1027",
    customer: { name: "Harsh Vardhan", email: "harsh.v@example.com", tier: "Silver" },
    amount: 1850,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 1,
    customerSuccessRate: 0.80,
    previousSuccessfulPayments: 6,
    transactionAge: 2.9,
    timestamp: new Date(Date.now() - 2.9 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1028",
    customer: { name: "Tanvi Saxena", email: "tanvi.s@example.com", tier: "Gold" },
    amount: 9499,
    paymentMethod: "Net Banking",
    failureReason: "network_error",
    retryCount: 0,
    customerSuccessRate: 0.91,
    previousSuccessfulPayments: 17,
    transactionAge: 0.6,
    timestamp: new Date(Date.now() - 0.6 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1029",
    customer: { name: "Abhinav Prasad", email: "abhinav.p@example.com", tier: "Bronze" },
    amount: 3800,
    paymentMethod: "UPI",
    failureReason: "insufficient_funds",
    retryCount: 2,
    customerSuccessRate: 0.42,
    previousSuccessfulPayments: 3,
    transactionAge: 16.0,
    timestamp: new Date(Date.now() - 16.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1030",
    customer: { name: "Rhea Iyer", email: "rhea.i@example.com", tier: "Gold" },
    amount: 13500,
    paymentMethod: "Card",
    failureReason: "bank_declined",
    retryCount: 0,
    customerSuccessRate: 0.89,
    previousSuccessfulPayments: 14,
    transactionAge: 1.1,
    timestamp: new Date(Date.now() - 1.1 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1031",
    customer: { name: "Yash Nambiar", email: "yash.n@example.com", tier: "Silver" },
    amount: 4200,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 0,
    customerSuccessRate: 0.86,
    previousSuccessfulPayments: 10,
    transactionAge: 0.4,
    timestamp: new Date(Date.now() - 0.4 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1032",
    customer: { name: "Bhavna Jain", email: "bhavna.j@example.com", tier: "Bronze" },
    amount: 1999,
    paymentMethod: "Wallet",
    failureReason: "authentication_failure",
    retryCount: 1,
    customerSuccessRate: 0.55,
    previousSuccessfulPayments: 4,
    transactionAge: 9.8,
    timestamp: new Date(Date.now() - 9.8 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1033",
    customer: { name: "Alok Sengupta", email: "alok.s@example.com", tier: "Platinum" },
    amount: 28900,
    paymentMethod: "Card",
    failureReason: "network_error",
    retryCount: 0,
    customerSuccessRate: 0.99,
    previousSuccessfulPayments: 45,
    transactionAge: 0.2,
    timestamp: new Date(Date.now() - 0.2 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1034",
    customer: { name: "Jasleen Kaur", email: "jasleen.k@example.com", tier: "Gold" },
    amount: 7200,
    paymentMethod: "UPI",
    failureReason: "bank_declined",
    retryCount: 1,
    customerSuccessRate: 0.88,
    previousSuccessfulPayments: 12,
    transactionAge: 3.5,
    timestamp: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1035",
    customer: { name: "Chirag Trivedi", email: "chirag.t@example.com", tier: "Silver" },
    amount: 5100,
    paymentMethod: "Card",
    failureReason: "expired_card",
    retryCount: 0,
    customerSuccessRate: 0.83,
    previousSuccessfulPayments: 8,
    transactionAge: 6.7,
    timestamp: new Date(Date.now() - 6.7 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1036",
    customer: { name: "Madhav Menon", email: "madhav.m@example.com", tier: "Bronze" },
    amount: 2750,
    paymentMethod: "UPI",
    failureReason: "insufficient_funds",
    retryCount: 0,
    customerSuccessRate: 0.60,
    previousSuccessfulPayments: 5,
    transactionAge: 4.8,
    timestamp: new Date(Date.now() - 4.8 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1037",
    customer: { name: "Trisha Dutta", email: "trisha.d@example.com", tier: "Gold" },
    amount: 11999,
    paymentMethod: "Net Banking",
    failureReason: "bank_declined",
    retryCount: 0,
    customerSuccessRate: 0.94,
    previousSuccessfulPayments: 19,
    transactionAge: 1.5,
    timestamp: new Date(Date.now() - 1.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1038",
    customer: { name: "Nikhil Kamath", email: "nikhil.k@example.com", tier: "Platinum" },
    amount: 35000,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 0,
    customerSuccessRate: 0.97,
    previousSuccessfulPayments: 34,
    transactionAge: 0.3,
    timestamp: new Date(Date.now() - 0.3 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1039",
    customer: { name: "Richa Chadha", email: "richa.c@example.com", tier: "Silver" },
    amount: 3299,
    paymentMethod: "Card",
    failureReason: "authentication_failure",
    retryCount: 1,
    customerSuccessRate: 0.72,
    previousSuccessfulPayments: 6,
    transactionAge: 5.5,
    timestamp: new Date(Date.now() - 5.5 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1040",
    customer: { name: "Siddhesh Parab", email: "siddhesh.p@example.com", tier: "Bronze" },
    amount: 1650,
    paymentMethod: "Wallet",
    failureReason: "network_error",
    retryCount: 2,
    customerSuccessRate: 0.45,
    previousSuccessfulPayments: 2,
    transactionAge: 11.2,
    timestamp: new Date(Date.now() - 11.2 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1041",
    customer: { name: "Swati Somani", email: "swati.s@example.com", tier: "Gold" },
    amount: 16800,
    paymentMethod: "Card",
    failureReason: "bank_declined",
    retryCount: 1,
    customerSuccessRate: 0.91,
    previousSuccessfulPayments: 15,
    transactionAge: 2.0,
    timestamp: new Date(Date.now() - 2.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1042",
    customer: { name: "Gautam Adani", email: "gautam.a@example.com", tier: "Platinum" },
    amount: 7999,
    paymentMethod: "Card",
    failureReason: "bank_declined",
    retryCount: 1,
    customerSuccessRate: 0.90,
    previousSuccessfulPayments: 16,
    transactionAge: 1.0,
    timestamp: new Date(Date.now() - 1.0 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1043",
    customer: { name: "Pallavi Ghosh", email: "pallavi.g@example.com", tier: "Silver" },
    amount: 4800,
    paymentMethod: "UPI",
    failureReason: "upi_timeout",
    retryCount: 0,
    customerSuccessRate: 0.85,
    previousSuccessfulPayments: 9,
    transactionAge: 0.7,
    timestamp: new Date(Date.now() - 0.7 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1044",
    customer: { name: "Chetan Bhagat", email: "chetan.b@example.com", tier: "Gold" },
    amount: 6200,
    paymentMethod: "Card",
    failureReason: "expired_card",
    retryCount: 0,
    customerSuccessRate: 0.88,
    previousSuccessfulPayments: 13,
    transactionAge: 7.1,
    timestamp: new Date(Date.now() - 7.1 * 3600 * 1000).toISOString(),
    status: "failed"
  },
  {
    id: "TXN-1045",
    customer: { name: "Sunita Williams", email: "sunita.w@example.com", tier: "Platinum" },
    amount: 19500,
    paymentMethod: "Net Banking",
    failureReason: "network_error",
    retryCount: 0,
    customerSuccessRate: 0.96,
    previousSuccessfulPayments: 25,
    transactionAge: 0.4,
    timestamp: new Date(Date.now() - 0.4 * 3600 * 1000).toISOString(),
    status: "failed"
  }
];

module.exports = { initialTransactions };
